steps:
- name: node:10.15.1
  entrypoint: yarn
  args: ['install']

- name: node:10.15.1
  entrypoint: yarn
  args: ['test:unit']

- name: node:10.15.1
  entrypoint: yarn
  args: ['build']

tags: ['$REPO_NAME', '$SHORT_SHA']
logsBucket: 'gs://bestqa_cloudbuild/build_log'